# save as .github/workflows/push_pull_request.yml of arbitrary Raku module repositories
name: push_pull_request

# ensure only one of this jobs runs for branch
concurrency:
  group: ${{ github.name }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    paths:
      - 'lib/**'
      - 't/**'
  pull_request:

jobs:
  run-all-os:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    uses: zero-overhead/App-Workflows-Github/.github/workflows/install_module.yml@main
    with:
      OS: ${{ matrix.os }}
      verbosity: error