# save as .github/workflows/user_run.yml of arbitrary Raku module repositories
name: user_run

on:
  workflow_dispatch: # run on Terminal: gh workflow run 'user_run' --ref branch-name -f verbosity=debug -f os=windows
    inputs:
      verbosity:
        description: zef verbosity
        required: false
        default: error
        type: choice
        options: 
        - error
        - warn
        - info
        - verbose
        - debug
      os:
        description: Operating System to run on
        required: false
        default: ubuntu
        type: choice
        options: 
        - ubuntu
        - macos
        - windows

jobs:
  run-one-os:
    uses: zero-overhead/App-Workflows-Github/.github/workflows/user_on_OS.yml@main
    with:
      OS: ${{ inputs.os || 'ubuntu' }}
      verbosity: ${{ inputs.verbosity || 'error' }}