# save as .github/workflows/user_run_all.yml of arbitrary Raku module repositories
name: user_run_all

# ensure only one of this jobs runs for branch
concurrency:
  group: ${{ github.name }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  schedule: # schedule a monthly run - just keeping an eye on long-time-not-touched repositories
    - cron: '50 2 25 * *'
  push:
  pull_request:

jobs:
  run-all-os:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    uses: zero-overhead/App-Workflows-Github/.github/workflows/user_on_OS.yml@main
    with:
      OS: ${{ matrix.os }}
      verbosity: error